StarScaff/StarScaff/Controllers/AdminController.cs
using System;
using System.IO;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Security;
using System.Web.Mvc;
using StarScaff.Models;
using StarScaff.Database_Access_Layer;
using System.Net;
using System.Net.Mail;
using System.Net.Mime;
using System.Collections.Specialized;
using System.Text;
using System.Web.Helpers;

namespace StarScaff.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin                
        string SuccessMsg = "", ErrorMsg = "", sender="", result ="";
        string OTPCode, status;
        public static string to;
        db loginLayer = new db();
        Account accModel = new Account();
        DataTable dt = new DataTable(); 
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Verify(Account acc)
        {
            return View();
        }
        [HttpPost]
        public JsonResult SubmitLoginData(string UserName, string Password )
        {
            try
            {
                Account um = new Account();
                dt = loginLayer.LoginDetails(UserName, Password);
                if (dt.Rows.Count >0)
                {
                    Session["ID"] = um.ID.ToString();                 
                    FormsAuthentication.SetAuthCookie(UserName, false);
                    accModel.SuccessMsg = "Successfully Login.";
                }
                else
                {
                    ModelState.AddModelError("", "Invalid Username And Password.");
                    accModel.ErrorMsg = "Invalid Username And Password.";
                }

            }
            catch (Exception ex)
            {
                accModel.ErrorMsg = ex.Message;                
            }
            return Json(accModel, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            Session.RemoveAll();
            Response.ExpiresAbsolute = DateTime.Now.AddDays(-1d);
            Response.Expires = -1500;
            Response.CacheControl = "no-cache";
            //FormsAuthentication.SignOut();
            //return RedirectToAction("Login");
            return View();
        }
        
        #region Change Password        
        public ActionResult ChangePassword()
        {
            return View();
        }        
        [HttpPost]
        public JsonResult changepassword(string old_pwd, string new_pwd, string c_pwd)
        {
            string SuccessMsg = "", ErrorMsg = "";
            try
            {
                string msg = loginLayer.changepassword(old_pwd, new_pwd, c_pwd);
                string[] response = msg.Split(',');
                if (response[0] == "Success")
                {                    
                        SuccessMsg = response[1];                    
                }
                else
                {
                    ErrorMsg = response[1]; 
                }
                return Json(new { SuccessMsg, ErrorMsg }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                ErrorMsg = "Error," + ex.ToString();
                return Json(new { SuccessMsg, ErrorMsg }, JsonRequestBehavior.AllowGet);
            }

        }
        #endregion
        public JsonResult CreateUserRegistraion(UserModel objUserModel)
        {            
            List<UserModel> UserRegistrationlist = new List<UserModel>();
            UserRegistrationlist.Add(objUserModel);
            ListtoDataTableConverter converter = new ListtoDataTableConverter();
            DataTable dt = new DataTable();
            dt = converter.ToDataTable(UserRegistrationlist);
            
            Account mm = new Account();
            string res = "";
            try
            {
                res = loginLayer.CreateUserRegistration(dt);
                
                string[] response = res.Split(',');
                if (response[0] == "Success")
                {
                    mm.SuccessMsg = response[1];
                }
                else if (response[0] == "Error")
                {
                    mm.ErrorMsg = response[1];
                }                
            }
            catch (Exception ex)
            {
                mm.ErrorMsg = ex.Message;
            }
            return Json(mm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ForgotPassword()
        {
            return View();
        }
        public JsonResult Forgot_Password(string tomail)
        {
            string senderEmail = System.Configuration.ConfigurationManager.AppSettings["SenderEmail"].ToString();
            string senderPassword = System.Configuration.ConfigurationManager.AppSettings["SenderPassword"].ToString();           
            string messageBody = "";
            Random rand = new Random();
            OTPCode = (rand.Next(999999)).ToString();
            MailMessage message = new MailMessage();            
            to = tomail;            
            message.IsBodyHtml = false;
            message.BodyEncoding = UTF8Encoding.UTF8;
            messageBody = "Your reset OPT Code is:" + OTPCode;
            message.To.Add(to);
            message.From = new MailAddress(senderEmail);            
            message.Body = messageBody;
            message.Subject = "Forgot password code";            
            SmtpClient smtp = new SmtpClient("smtp.mail.yahoo.com", 465);
            smtp.EnableSsl = true;
            smtp.Timeout = 100000;
            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtp.UseDefaultCredentials = false;
            smtp.Credentials = new NetworkCredential(senderEmail, senderPassword);
            smtp.Send(message);
            try
            {                
                SuccessMsg = "Code send successfully.";
            }
            catch (SmtpException ex)
            {
                ErrorMsg = ex.Message;
            }
            return Json(new { SuccessMsg, ErrorMsg }, JsonRequestBehavior.AllowGet);
        }        
        public ActionResult VerifyCode(string tomail, string vcode)
        {
            Account accModel = new Account();
            if (OTPCode == vcode.ToString())
            {
                to = tomail.ToString();
            }
            else
            {
                ErrorMsg = "Wrong Code.";
            }
            return RedirectToAction("/Admin/ChangePassword");
        }        
    }
}

StarScaff/StarScaff/Controllers/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StarScaff.Controllers
{
    public class ProductionController : Controller
    {
        // GET: Production
        public ActionResult PhotoGallery()
        {
            return View();
        }
        public ActionResult RotatePhotoGallery()
        {
            return View();
        }
        public ActionResult TextRotate()
        {
            return View();
        }
        public ActionResult PhotoRotate()
        {
            return View();
        }
        public ActionResult InfiniteImageLoop()
        {
            return View();
        }
        public ActionResult ImageGalleryZoom()
        {
            return View();
        }
        public ActionResult CardRotate()
        {
            return View();
        }
        public ActionResult PhotoCovers()
        {
            return View();
        }
        
        public ActionResult Perspective3DMouseOver()
        {
            return View();
        }
        public ActionResult GlassEffect()
        {
            return View();
        }
        public ActionResult ImageHover()
        {
            return View();
        }
        public ActionResult Image3D()
        {
            return View();
        }             
    }
}

StarScaff/StarScaff/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Assets/CSS/Style.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <title>Star Scaff</title>

    <style type="text/css">
        * {
            padding: 0px;
            margin: 0px;
        }

        body {
            font-family: Arial,sans-serif;
        }

        header {
            overflow: hidden;
            position: fixed;
            width: 100%;
            height: 80px;
            background-color: #f1c40f;
        }

        .openbtn {
            font-size: 20px;
            cursor: pointer;
            background-color: #f1c40f;
            color: white;
            border: none;
            margin-left: 5px;
            outline: none;
        }

        #header {
            line-height: 80px;
            transition: margin-left .5s;
            margin-left: 250px;
        }

        .accordian {
            width: 250px;
            height: 100%;
            position: fixed;
            z-index: 1;
            margin-top: 80px;
            top: 0;
            left: 0;
            background-image: linear-gradient(#f1c40f,#f39c12);
            transition: 0.5s;
            padding-top: 80px;
            overflow-x: hidden;            
        }
        #accordian::-webkit-scrollbar {
        width:15px;
    }
    #accordian::-webkit-scrollbar-track {
        border-radius:10px;
        background:#f5f5f5;
        box-shadow:inset 0 0 6px rgba(0,0,0,0.3);
    }
    #accordian::-webkit-scrollbar-thumb {
        border-radius:10px;
        height:20px;
        background:linear-gradient(red,yellow); 
        box-shadow:inset 0 0 6px rgba(0,0,0,0.3);       
    }
    #accordian::-webkit-scrollbar-corner {        
        background:linear-gradient(red,yellow);               
    }

        footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 40px;
        }
    </style>
    <script type="text/javascript">
        function togglebar() {
            var element = document.getElementById("accordian");
            var shown = element.getAttribute("data-isshown");
            if (shown == "true") {
                element.setAttribute("data-isshown", "false");
                document.getElementById("accordian").style.width = "250px";
                document.getElementById("header").style.marginLeft = "250px";
            }
            else {
                element.setAttribute("data-isshown", "true");
                document.getElementById("accordian").style.width = "0px";
                document.getElementById("header").style.marginLeft = "0px";
            }
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#accordian h3").click(function () {
                //Slide up all the link lists
                $("#accordian ul ul").slideUp();
                //Slide down the link list below the h3 clicked - only if it's closed
                if (!$(this).next().is(":visible")) {
                    $(this).next().slideDown();
                }
            })
        })

    </script>
    <style type="text/css">
        * {
            padding: 0;
            margin: 0;
            text-decoration: none;
            list-style: none;
            box-sizing: border-box;
        }

        body {
            font-family: Arial,sans-serif;
        }

        header {
            /*overflow:hidden;
            position:fixed;*/
            width: 100%;
            height: 80px;
            background-color: #f1c40f;
        }

        label.logo {
            color: white;
            font-size: 30px;
            line-height: 80px;
            padding: 0 100px;
            font-weight: bold;
        }

        .logo img {
            position: absolute;
            margin-top: 0px;
            margin-left: 0px;
        }
    </style>
    <style type="text/css">
        .logo {
            font-weight: 900;
            font-size: 3.5em;
        }

            .logo .letter {
                display: inline-block;
                line-height: 1em;
            }
    </style>
    <style type="text/css">
        /*.imgbox {
            width:150px;
            height:80px;
            background:white;
            animation:logo-animation 2s ease-in-out 1s infinite alternate;
        }
            .imgbox:hover {
                animation-play-state:paused;
            }
        @@keyframes logo-animation {
            0% {border-radius:0%
            }
            100% {
                border-radius:50%;background-color:tomato;color:white;
            }
        }*/
        #deptext {
            /*background-image:linear-gradient(red,yellow);
            border:1px solid black;
            border-radius:5px;
            box-decoration-break:clone;*/
            float:left; 
            padding-left:300px;           
            margin-right:10px;
        }

    </style>
    <script type="text/javascript">
        $(function () {

            var textWrapper = document.querySelector('.logo');
        textWrapper.innerHTML = textWrapper.textContent.replace(/\S/g, "<span class='letter'>$&</span>");

        anime.timeline({ loop: true })
          .add({
              targets: '.logo .letter',
              scale: [4, 1],
              opacity: [0, 1],
              translateZ: 0,
              easing: "easeOutExpo",
              duration: 950,
              delay: (el, i) => 70 * i
          }).add({
              targets: '.logo',
              opacity: 0,
              duration: 1000,
              easing: "easeOutExpo",
              delay: 1000
          });
        });
    </script>

</head>
<body>
    <header>
        <div id="header">
            <div style="float:left;">
                <button type="button" name="button" class="openbtn" onclick="togglebar()"><i class="fas fa-bars"></i></button>
            </div>
            <div class="imgbox" style="float:left;margin-left:30px;padding-bottom:1px;">
                @*<img src="~/Assets/Images/star-scaff.jpg" style="height:60px;width:150px;" />*@
                <img src="~/Assets/Images/nusadstar.png" style="height:80px;width:150px;" />
                @*<img src="~/Assets/Images/Nusad.jpg" style="height:80px;width:150px;" />*@
            </div>
            <div style="float:left">
                <label class="logo" style="margin-right:0px;">STAR SCAFF SHUTTERING & FABRICATION</label>
            </div>                       
        </div>
    </header>
    <div id="accordian" class="accordian">
        <ul>
            <li>
                <h3><span class="fa fa-dashboard"></span>Dashboard</h3>
                <ul>
                    <li><a href="@Url.Action("Dashboard","Dashboard")">Dash board</a></li>                                        
                </ul>
            </li>
            <li class="active">
                <h3><span class="fas fa-user-lock"></span>Admin</h3>
                <ul>
                    <li><a href="@Url.Action("Login","Admin")"> Login </a></li>                    
                    <li><a href="@Url.Action("Logout","Admin")">Logout</a></li>
                    <li><a href="@Url.Action("ChangePassword","Admin")">Change Password</a></li>                   
                </ul>
            </li>
            <li>
                <h3><span class="fa fa-home"></span>Home</h3>
                <ul>                                     
                    <li><a href="@Url.Action("Index","Home")"> Home </a></li>                                       
                    <li><a href="@Url.Action("AboutUs","Home")"> About Us </a></li>
                    <li><a href="@Url.Action("PresidentProfile","Home")"> MD Profile </a></li>
                </ul>
            </li>
            <li>
                <h3><span class="fas fa-prescription"></span>Products</h3>
                <ul>                    
                    <li><a href="@Url.Action("PhotoGallery","Production")"> Photo Gallery </a></li>
                    <li><a href="@Url.Action("TextRotate","Production")"> Css Text</a></li>
                    <li><a href="@Url.Action("InfiniteImageLoop","Production")">MKSS MEMBERS</a></li>
                    <li><a href="@Url.Action("ImageGalleryZoom","Production")">Image Gallery Zoom</a></li>
                    <li><a href="@Url.Action("CardRotate","Production")">Card Rotate</a></li>                                                            
                    <li><a href="@Url.Action("Perspective3DMouseOver","Production")">Image Mouse Over</a></li>
                    <li><a href="@Url.Action("GlassEffect","Production")">Glass Effect</a></li>
                    <li><a href="@Url.Action("ImageHover","Production")">Image Hover</a></li>
                    <li><a href="@Url.Action("Image3D","Production")">Image 3D</a></li> 
                    <li><a href="@Url.Action("PhotoCovers","Production")">View All</a></li>                   
                </ul>
            </li>            
            @*<li>
                <h3><span class="fa fa-calendar"></span>Calendar</h3>
                <ul>
                    <li><a href="#"> Item 1 </a></li>
                    <li><a href="#"> Item 2 </a></li>
                    <li><a href="#"> Item 3 </a></li>
                    <li><a href="#"> Item 4 </a></li>
                </ul>
            </li>
            <li>
                <h3><span class="fa fa-heart"></span>Favorites</h3>
                <ul>
                    <li><a href="#"> Item 1 </a></li>
                    <li><a href="#"> Item 2 </a></li>
                    <li><a href="#"> Item 3 </a></li>
                    <li><a href="#"> Item 4 </a></li>
                </ul>
            </li>*@
        </ul>
        @*<img src="~/Assets/Images/nusadstar1.png" style="margin-left:10px; height:250px;width:250px;padding-right:20px;padding-top:10px;" />*@
    </div>
    <div class="main" style="margin-left:250px;">
        @RenderBody();
    </div>
    <footer style="background-color:#0984e3;text-align:center;padding:10px;">
        <span id="deptext">Developed by Manoj Kumar, Contact No.:8860717253</span>
        <span style="float:right;">© 2020 Star Scaff Shuttering & Fabrication, All right reserved</span>        
    </footer>
</body>
</html>